<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9cd6d9c36cbf4cead81b430c30086345
{
    public static $prefixLengthsPsr4 = array (
        'w' => 
        array (
            'wpcdc\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'wpcdc\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9cd6d9c36cbf4cead81b430c30086345::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9cd6d9c36cbf4cead81b430c30086345::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9cd6d9c36cbf4cead81b430c30086345::$classMap;

        }, null, ClassLoader::class);
    }
}
